In [ ]:
import numpy as np
import pandas as pd

# here is the link to my google colab 
# https://colab.research.google.com/drive/1yMefyWgomilm8aXjZ37DIK-7u8aAu-oh?usp=sharing
from google.colab import drive
drive.mount('/content/drive')

# a. Place the following data into a file and read the data into the matrix from a file called “Data.txt”
file_name = '/content/drive/MyDrive/CS512/Data.txt'

og_matrix = np.loadtxt(file_name)
df = pd.DataFrame(og_matrix)
print("The original matrix is as follows:")
df

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
The original matrix is as follows:

      0     1     2     3     4     5     6     7     8     9
0  26.0   8.0   2.0  12.0  67.0  89.0   8.0  78.0  56.0   7.0
1  13.0   9.0  57.0  11.0  10.0  99.0  15.0  90.0  88.0  15.0
2   6.0  23.0  28.0  32.0  53.0  59.0  48.0  41.0  60.0  62.0
3  17.0   6.0  93.0  95.0  20.0  25.0  29.0  31.0  71.0  30.0
4  16.0  13.0  26.0  22.0  14.0  66.0  71.0   5.0   2.0  91.0
5  40.0  53.0  22.0  18.0  44.0  73.0  77.0  84.0  89.0  88.0
6  34.0  54.0  89.0   8.0  65.0  74.0  96.0   3.0   1.0  80.0
7  14.0  28.0  39.0  44.0  86.0  88.0  75.0  77.0  93.0   4.0
8  65.0  66.0  82.0  97.0  51.0  41.0  28.0  33.0  55.0  79.0
9  13.0  48.0  71.0  98.0  26.0  38.0  55.0  59.0   7.0  19.0

In [40]:
# b. Select three columns, columns 3, 1, and 9, sort them in ascending order of column 3
# and make a matrix of 10 by 3 using these three columns and call it Matrix1.
matrix1 = df.iloc[:,[2,0,8]]
print("The first three random numbers are 3, 1, and 9 which makes Matrix 1 as follows:")
matrix1

The first three random numbers are 3, 1, and 9 which makes Matrix 1 as follows:

      2     0     8
0   2.0  26.0  56.0
1  57.0  13.0  88.0
2  28.0   6.0  60.0
3  93.0  17.0  71.0
4  26.0  16.0   2.0
5  22.0  40.0  89.0
6  89.0  34.0   1.0
7  39.0  14.0  93.0
8  82.0  65.0  55.0
9  71.0  13.0   7.0

In [41]:
print("The sorted version of Matrix1 in ascending order of its first column (column 3 of the original matrix) is:")
matrix1_sorted = matrix1.sort_values(by=2,ascending=True)
matrix1_sorted

The sorted version of Matrix1 in ascending order of its first column (column 3 of the original matrix) is:

      2     0     8
0   2.0  26.0  56.0
5  22.0  40.0  89.0
4  26.0  16.0   2.0
2  28.0   6.0  60.0
7  39.0  14.0  93.0
1  57.0  13.0  88.0
9  71.0  13.0   7.0
8  82.0  65.0  55.0
6  89.0  34.0   1.0
3  93.0  17.0  71.0

In [42]:
# # c. Select another set of three columns, columns 5, 2, 7, sort them in descending order of
# column 5 and make a matrix of 10 by 3 using these three columns - Call it Matrix2.
matrix2 = df.iloc[:,[4,1,6]]
print("Suppose the next set of three random numbers are 5, 2, and 7. So you your output should prints:")
matrix2

Suppose the next set of three random numbers are 5, 2, and 7. So you your output should prints:

      4     1     6
0  67.0   8.0   8.0
1  10.0   9.0  15.0
2  53.0  23.0  48.0
3  20.0   6.0  29.0
4  14.0  13.0  71.0
5  44.0  53.0  77.0
6  65.0  54.0  96.0
7  86.0  28.0  75.0
8  51.0  66.0  28.0
9  26.0  48.0  55.0

In [43]:
print("Sorting Matrix 2 in descending order of its first column (column 5 of the original matrix) we get:")
matrix2_sorted = matrix2.sort_values(by=4,ascending=False)
matrix2_sorted

Sorting Matrix 2 in descending order of its first column (column 5 of the original matrix) we get:

      4     1     6
7  86.0  28.0  75.0
0  67.0   8.0   8.0
6  65.0  54.0  96.0
2  53.0  23.0  48.0
8  51.0  66.0  28.0
5  44.0  53.0  77.0
9  26.0  48.0  55.0
3  20.0   6.0  29.0
4  14.0  13.0  71.0
1  10.0   9.0  15.0

In [44]:
# d. Add the two sorted matrices to each other and put the result into another 10 by 3
# matrix call it matrix3. No need to sort Matrix 3.
Matrix1 = matrix1_sorted.to_numpy()
Matrix2 = matrix2_sorted.to_numpy()
Matrix3 = Matrix1 + Matrix2
print("Adding the contents of the Matrix1 and Matrix2, and put the result in one column Matrix called Matrix 3:")
print(Matrix3)

Adding the contents of the Matrix1 and Matrix2, and put the result in one column Matrix called Matrix 3:
[[ 88.  54. 131.]
 [ 89.  48.  97.]
 [ 91.  70.  98.]
 [ 81.  29. 108.]
 [ 90.  80. 121.]
 [101.  66. 165.]
 [ 97.  61.  62.]
 [102.  71.  84.]
 [103.  47.  72.]
 [103.  26.  86.]]

In [45]:
# e. Add the content of each row of Matrix 3 and put it into a new 10 by 1 matrix call it Matrix 4.
Matrix4 = np.sum(Matrix3, axis=1, keepdims=True)
print("After adding the content of matrix 3 to get the matrix 4 we get:")
print(Matrix4)

After adding the content of matrix 3 to get the matrix 4 we get:
[[273.]
 [234.]
 [259.]
 [218.]
 [291.]
 [332.]
 [220.]
 [257.]
 [222.]
 [215.]]

In [46]:
# f. Sort Matrix4 in ascending order
matrix4_sorted = np.sort(Matrix4, axis=0)
print("Sorting matrix 4 in ascending order:")
print(matrix4_sorted)

Sorting matrix 4 in ascending order:
[[215.]
 [218.]
 [220.]
 [222.]
 [234.]
 [257.]
 [259.]
 [273.]
 [291.]
 [332.]]